openapi: 3.0.0
info:
  title: 'Boilerplate API'
  version: 1.0.0
paths:
  /:
    get:
      summary: 'Get welcome message'
      operationId: 5aeb21eb14626d47415174baf0626d95
      responses:
        '200':
          description: 'Get welcome message'
